name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gobarber-web
    steps:
      - name: Use current action
        uses: getsentry/action-eslint-fix@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
